// Person
POST http://localhost:8080/v1/persons/create
content-type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNvbnRhY3RvQGdtYWlsLmNvbSIsImV4cCI6MTY0Njc4Mzk0MiwiaXNzIjoiRWR0ZWFtIn0.dFuXz_vO4TaOtv8Q79Z_bbzYW338PMOqG3UJfgzU4EOf6ZhiTlTIebJlLWwllPA-BohJAxYLLhvO4UzRedDMjyGgKKfifPfnlEIgzh3eEYDRgaiza09AzgvpcDOEjTszrQYzbamfCFKirymZbD29oCCBeMHgPQoSdzU9Ak2d9uc

{
    "name": "Ian Rivas",
    "age": 27,
    "communities": [
        {"name": "platzi"},
        {"name": "edteam"}
    ]
}

###
GET http://localhost:8080/v1/persons/get-all

###
PUT http://localhost:8080/v1/persons/update?id=1
content-type: application/json

{
    "name": "Erick Rivas",
    "age": 26,
    "communities": [
        {"name": "platzi"},
        {"name": "edteam"}
    ]
}
###
DELETE http://localhost:8080/v1/persons/delete?id=1

###

// Login - con esto generas el token para el Post de Person
POST http://localhost:8080/v1/login
content-type: application/json

{
    "email": "contacto@gmail.com",
    "password": "123456"
}
